/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.backbase.oss.boat

import org.gradle.api.Plugin
import org.gradle.api.Project

/**
 * A simple 'hello world' plugin.
 */
class GradlePlugin implements Plugin<Project> {
    static final String ID = GradlePlugin.name

    @Override
    void apply(Project project) {
        project.extensions.create("boat", GradleExtension.class)
    }
}
