/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.backbase.oss.boat

import org.gradle.testfixtures.ProjectBuilder
import org.gradle.api.Project
import spock.lang.Specification

class GradlePluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply(GradlePlugin.package.name)

        then:
        project.extensions.findByName("boat") != null
    }
}
